### ISSUE TITLE
Last menu item needs to have same behavior as "I want details" button.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ono-Internet-Marketing-Site#13]
![image](https://user-images.githubusercontent.com/1911594/29166422-921f8f0a-7dc6-11e7-8c83-ebb81ad4d998.png)
We need to show contact form the same way as with other "details" button.

**Comment by VladimirWebDev** [comment]
@talovdat Can You provide title for this contact form..?

**Comment by talovdat** [comment]
Popup form title : לקבלת מידע מיועץ לימודים על מסלול ההכשרה

Same title that goes for the i want details button.
