### ISSUE TITLE
Fix 'send details' button behavior on dialog 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-Internet-Marketing-Site#20]
Nothing happens when clicking on the 'send details' button in dialog. 
Button behavior should send details and download a PDF file. 

![image](https://user-images.githubusercontent.com/26923359/29250041-089cb61a-8044-11e7-9558-7d709ce0c5d6.png)

**Comment by MeanEYE** [comment]
The configuration is to allow download after successful submission. Since SendGrid is not configured, no submission happens. Regardless I'll configure it today and then you can retest.
