### ISSUE TITLE
Missing files.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-Internet-Marketing-Site#8]
Site is missing  Tutor images. 
Qualiymatch images.
Syllabus.

All have been provided via email.

**Comment by talovdat** [comment]
since the email is in Hebrew just go by the next explanation:

jpg - Tutor images. 
jpg(file name: ScreenHunter) -  qualiymatch images.
pdf - Syllabus

**Comment by MeanEYE** [comment]
It would be helpful if you can include screen shots of parts of the page where these go.

**Comment by talovdat** [comment]
Tutor images:
![image](https://user-images.githubusercontent.com/26923359/28976032-fcfebcdc-7944-11e7-96aa-e9cf5d915148.png)


Qualiymatch image:
![image](https://user-images.githubusercontent.com/26923359/28976072-2d09121a-7945-11e7-9263-91f7446c2b41.png)


Syllabus pdf downloads when clicking each and one of the next buttons:
![image](https://user-images.githubusercontent.com/26923359/28976146-6e877038-7945-11e7-9429-80a26f99c056.png)
